---
title: "Tech Financials"
author: "Remya"
date: "9/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(haven)
library(psych)
library(here)
# always load the packages in this default intro: chunk
```

# Reading Data
```{r , echo=FALSE}
d1 <- haven::read_dta("tech_co_cstat_dta.zip") # function read_dta which is a Stata file belongs to the package haven

```


```{r , echo=FALSE}
class(d1)
```

```{r}
names(d1)
```

```{r}
head(d1)
```

```{r}
tail(d1, n=7)
```
```{r}
attributes(d1$gvkey)# give the attributes of the variable 'gvkey' such as label and format.stata
```
```{r}
attributes(d1$datadate)# this gives one more attribute other than label and format.stata ie.class of the variable
```
```{r}
attributes(d1$datadate)$label <- "Fiscal year end date"

```

```{r}
attributes(d1$datadate)$label <- NULL

```

```{r}
attributes(d1$datadate)
```
```{r}
glimpse(d1)
```

```{r}
psych::describe(d1)
```

```{r}
table(d1$gvkey)# does not give any idea abt data
```

```{r}
table(d1$conm)# frequency table for much clear idea about the data
```

```{r}
count(d1, conm)
```

### Select() for subsetting
```{r}
d2 <- select(d1,conm,datadate,sale,xrd)
```

```{r}
names(d2)
```

```{r}
d2 <- select(d1,-gvkey)
```
 
```{r}
d3 <- d1 %>%
  select(-gvkey) %>% 
  head() 

d4 <- head(select(d1,-gvkey))# this is same as using pipe
```

```{r}
identical(d3, d4)
```

### Filter()
```{r}
mean(d1$sale, na.rm = FALSE)# missing value returns NA by default
```


```{r}
d5 <- d1 %>% 
  filter(sale > 0)# excludes negative and Zero values

# BAse R d1[d1$sale>0]
```

```{r}
mean(d5$sale)
```
```{r}
d6 <- d1 %>% 
  filter(!is.na(sale))

```


```{r , eval=FALSE}
!is.na(d1$sale)# code is same as d6 so instead of d1 can give d6 then we get 107 obs with true
  
```
 
### Mutate
 
```{r}
d7 <- d5 %>% 
  mutate(profit_margin = oibdp/sale)

```
 
```{r}
names(d7)# checking
```
 
```{r}
d7 <-  d5 %>% 
  mutate(profit_margin = oibdp/sale,
         cash_holding = che/at,
         rnd_intensity = xrd/sale,
         debt_lt = ifelse(is.na(dltt),0,dltt))# ifelse is Base R funtion not from dplyr
```

```{r}
head(d5$dltt)
```

```{r}
is.na(d5$dltt) %>% sum()
```
```{r}
# calcualting sales growth
d7 %>% 
  select(conm,datadate,sale) %>% 
  head(20)

```

```{r}
d8 <- d7 %>% 
  arrange(conm,datadate) %>% 
  group_by(conm) %>% 
  mutate(sale_gr = (sale - lag(sale))/lag(sale))
```

```{r}
d7 %>% 
  select(sale) %>%
  summarise(sale_mean = mean(sale),
            sale_median = median(sale),
            sale_sd = sd(sale))
```

```{r}
d7 %>% 
  select(sale,at,xrd) %>%
  summarise(across(everything(), mean))
```

```{r}
d7 %>% 
  group_by(conm) %>%
  summarise(sale_mean = mean(sale),
            sale_median = median(sale),
            sale_sd = sd(sale)) %>% 
              as.data.frame()
```

```{r}
d5 %>% 
    mutate(first_half_decade = ifelse(fyear<2015,1,0)) %>% 
    group_by(conm,first_half_decade) %>% 
    summarise(sale_mean = mean(sale),
            sale_median = median(sale),
            sale_sd = sd(sale))
```

